import type { Metadata } from "next";
import { Inter, Poppins, Pangolin } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { cx } from "@/utils";

const pangolin = Pangolin({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-pan",
});
const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-pop",
});
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-in",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cx(
          pangolin.variable,
          poppins.variable,
          inter.variable,
          "font-in bg-light dark:bg-dark",
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
